apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ilqj4tlwk-python 
  janus-idp.io/tekton: ilqj4tlwk-python
  backstage.io/kubernetes-id: ilqj4tlwk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ilqj4tlwk-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml