apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ilqj4tlwk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ilqj4tlwk-python 
  name: ilqj4tlwk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ilqj4tlwk-python 
